class DailyExplosiveVan {
  final String serialNumber;
  final String checkPoint;
  bool actionRequired;
  final String cgName;
  final String rectified;
  final String criticalParts;

  DailyExplosiveVan({
    required this.serialNumber,
    required this.checkPoint,
    required this.actionRequired,
    required this.cgName,
    required this.rectified,
    required this.criticalParts,
  });
}

List<DailyExplosiveVan> dailyExplosiveVan = [
  DailyExplosiveVan(
    serialNumber: '1',
    checkPoint: 'Hmr',
    actionRequired: false,
    cgName: 'Cg-12c-3442',
    rectified: 'Rectified',
    criticalParts: 'Critical parts life hrs.',
  ),
  DailyExplosiveVan(
    serialNumber: '2',
    checkPoint: 'Fist aid kit',
    actionRequired: false,
    cgName: 'Cg-12c-3442',
    rectified: 'Rectified',
    criticalParts: 'Critical parts life hrs.',
  ),
  DailyExplosiveVan(
    serialNumber: '3',
    checkPoint: 'Seat belt',
    actionRequired: false,
    cgName: 'Cg-12c-3442',
    rectified: 'Rectified',
    criticalParts: 'Critical parts life hrs.',
  ),
  DailyExplosiveVan(
    serialNumber: '4',
    checkPoint: 'Brake light',
    actionRequired: false,
    cgName: 'Cg-12c-3442',
    rectified: 'Rectified',
    criticalParts: 'Critical parts life hrs.',
  ),
  DailyExplosiveVan(
    serialNumber: '5',
    checkPoint: 'Audio visual alaram',
    actionRequired: false,
    cgName: 'Cg-12c-3442',
    rectified: 'Rectified',
    criticalParts: 'Critical parts life hrs.',
  ),
  DailyExplosiveVan(
    serialNumber: '6',
    checkPoint: 'Side mirror',
    actionRequired: false,
    cgName: 'Cg-12c-3442',
    rectified: 'Rectified',
    criticalParts: 'Critical parts life hrs.',
  ),
  DailyExplosiveVan(
    serialNumber: '7',
    checkPoint: 'Blind spot mirror',
    actionRequired: false,
    cgName: 'Cg-12c-3442',
    rectified: 'Rectified',
    criticalParts: 'Critical parts life hrs.',
  ),
  DailyExplosiveVan(
    serialNumber: '8',
    checkPoint: 'Battery cut off switch',
    actionRequired: false,
    cgName: 'Cg-12c-3442',
    rectified: 'Rectified',
    criticalParts: 'Critical parts life hrs.',
  ),
  DailyExplosiveVan(
    serialNumber: '9',
    checkPoint: 'Turbocharger guard',
    actionRequired: false,
    cgName: 'Cg-12c-3442',
    rectified: 'Rectified',
    criticalParts: 'Critical parts life hrs.',
  ),
  DailyExplosiveVan(
    serialNumber: '10',
    checkPoint: 'Service brake / parking brake',
    actionRequired: false,
    cgName: 'Cg-12c-3442',
    rectified: 'Rectified',
    criticalParts: 'Critical parts life hrs.',
  ),
  DailyExplosiveVan(
    serialNumber: '11',
    checkPoint: 'Wind shield wiper',
    actionRequired: false,
    cgName: 'Cg-12c-3442',
    rectified: 'Rectified',
    criticalParts: 'Critical parts life hrs.',
  ),
  DailyExplosiveVan(
    serialNumber: '12',
    checkPoint: 'Horn',
    actionRequired: false,
    cgName: 'Cg-12c-3442',
    rectified: 'Rectified',
    criticalParts: 'Critical parts life hrs.',
  ),
  DailyExplosiveVan(
    serialNumber: '13',
    checkPoint: 'Propeler shaft guard',
    actionRequired: false,
    cgName: 'Cg-12c-3442',
    rectified: 'Rectified',
    criticalParts: 'Critical parts life hrs.',
  ),
  DailyExplosiveVan(
    serialNumber: '14',
    checkPoint: 'Portable fire extinghisher- 02 types',
    actionRequired: false,
    cgName: 'Cg-12c-3442',
    rectified: 'Rectified',
    criticalParts: 'Critical parts life hrs.',
  ),
  DailyExplosiveVan(
    serialNumber: '15',
    checkPoint: 'Emergency switches',
    actionRequired: false,
    cgName: 'Cg-12c-3442',
    rectified: 'Rectified',
    criticalParts: 'Critical parts life hrs.',
  ),
  DailyExplosiveVan(
    serialNumber: '16',
    checkPoint: 'Front & back lights',
    actionRequired: false,
    cgName: 'Cg-12c-3442',
    rectified: 'Rectified',
    criticalParts: 'Critical parts life hrs.',
  ),
  DailyExplosiveVan(
    serialNumber: '17',
    checkPoint: 'Provision of earthing wire',
    actionRequired: false,
    cgName: 'Cg-12c-3442',
    rectified: 'Rectified',
    criticalParts: 'Critical parts life hrs.',
  ),
  DailyExplosiveVan(
    serialNumber: '18',
    checkPoint: 'No metalic parts in side of wooden chamber',
    actionRequired: false,
    cgName: 'Cg-12c-3442',
    rectified: 'Rectified',
    criticalParts: 'Critical parts life hrs.',
  ),
  DailyExplosiveVan(
    serialNumber: '19',
    checkPoint: 'Auto fire supression system',
    actionRequired: false,
    cgName: 'Cg-12c-3442',
    rectified: 'Rectified',
    criticalParts: 'Critical parts life hrs.',
  ),
  DailyExplosiveVan(
    serialNumber: '20',
    checkPoint: 'Engine oil level',
    actionRequired: false,
    cgName: 'Cg-12c-3442',
    rectified: 'Rectified',
    criticalParts: 'Critical parts life hrs.',
  ),
  DailyExplosiveVan(
    serialNumber: '21',
    checkPoint: 'Machine of any damage',
    actionRequired: false,
    cgName: 'Cg-12c-3442',
    rectified: 'Rectified',
    criticalParts: 'Critical parts life hrs.',
  ),
  DailyExplosiveVan(
    serialNumber: '22',
    checkPoint: 'Condition of cabin',
    actionRequired: false,
    cgName: 'Cg-12c-3442',
    rectified: 'Rectified',
    criticalParts: 'Critical parts life hrs.',
  ),
];
