class Hydraulics {
  final String title;
  final String volvo20;
  final String volvo21;
  final String volvo22;
  final String volvo23;
  final String hyundai390;
  final String hyundai210;
  final String action;
  bool volvo1;
  bool volvo2;
  bool volvo3;
  bool volvo4;
  bool hyundai1;
  bool hyundai2;
  bool actionTaken;
  bool toBeTaken;
  Hydraulics({
    required this.title,
    required this.volvo20,
    required this.volvo21,
    required this.volvo22,
    required this.volvo23,
    required this.hyundai390,
    required this.hyundai210,
    required this.action,
    required this.volvo1,
    required this.volvo2,
    required this.volvo3,
    required this.volvo4,
    required this.hyundai1,
    required this.hyundai2,
    required this.actionTaken,
    required this.toBeTaken,
  });
}

List<Hydraulics> hydraulics = [
  Hydraulics(
    title: 'Hyd oil leakages in tank, lines, Elements',
    volvo20: 'Mech. VOLVO-20',
    volvo21: 'Mech. VOLVO-21',
    volvo22: 'Mech. VOLVO-22',
    volvo23: 'Mech. VOLVO-23',
    hyundai390: 'Mech. HYUNDAI- 390',
    hyundai210: 'Mech. HYUNDAI-210',
    action: 'Action taken / to be taken',
    volvo1: false,
    volvo2: false,
    volvo3: false,
    volvo4: false,
    hyundai1: false,
    hyundai2: false,
    actionTaken: false,
    toBeTaken: false,
  ),
  Hydraulics(
    title: 'Check swing motor oil level',
    volvo20: 'Mech. VOLVO-20',
    volvo21: 'Mech. VOLVO-21',
    volvo22: 'Mech. VOLVO-22',
    volvo23: 'Mech. VOLVO-23',
    hyundai390: 'Mech. HYUNDAI- 390',
    hyundai210: 'Mech. HYUNDAI-210',
    action: 'Action taken / to be taken',
    volvo1: false,
    volvo2: false,
    volvo3: false,
    volvo4: false,
    hyundai1: false,
    hyundai2: false,
    actionTaken: false,
    toBeTaken: false,
  ),
  Hydraulics(
    title: 'Hyd oil cooler condition (fin block And leaks)',
    volvo20: 'Mech. VOLVO-20',
    volvo21: 'Mech. VOLVO-21',
    volvo22: 'Mech. VOLVO-22',
    volvo23: 'Mech. VOLVO-23',
    hyundai390: 'Mech. HYUNDAI- 390',
    hyundai210: 'Mech. HYUNDAI-210',
    action: 'Action taken / to be taken',
    volvo1: false,
    volvo2: false,
    volvo3: false,
    volvo4: false,
    hyundai1: false,
    hyundai2: false,
    actionTaken: false,
    toBeTaken: false,
  ),
  Hydraulics(
    title: 'Broom cylinders Condition',
    volvo20: 'Mech. VOLVO-20',
    volvo21: 'Mech. VOLVO-21',
    volvo22: 'Mech. VOLVO-22',
    volvo23: 'Mech. VOLVO-23',
    hyundai390: 'Mech. HYUNDAI- 390',
    hyundai210: 'Mech. HYUNDAI-210',
    action: 'Action taken / to be taken',
    volvo1: false,
    volvo2: false,
    volvo3: false,
    volvo4: false,
    hyundai1: false,
    hyundai2: false,
    actionTaken: false,
    toBeTaken: false,
  ),
  Hydraulics(
    title: 'Stick Cylinder Condition (Drift / Leakage)',
    volvo20: 'Mech. VOLVO-20',
    volvo21: 'Mech. VOLVO-21',
    volvo22: 'Mech. VOLVO-22',
    volvo23: 'Mech. VOLVO-23',
    hyundai390: 'Mech. HYUNDAI- 390',
    hyundai210: 'Mech. HYUNDAI-210',
    action: 'Action taken / to be taken',
    volvo1: false,
    volvo2: false,
    volvo3: false,
    volvo4: false,
    hyundai1: false,
    hyundai2: false,
    actionTaken: false,
    toBeTaken: false,
  ),
  Hydraulics(
    title: 'Bucket Cylinder Condition (Drift / Leakage)',
    volvo20: 'Mech. VOLVO-20',
    volvo21: 'Mech. VOLVO-21',
    volvo22: 'Mech. VOLVO-22',
    volvo23: 'Mech. VOLVO-23',
    hyundai390: 'Mech. HYUNDAI- 390',
    hyundai210: 'Mech. HYUNDAI-210',
    action: 'Action taken / to be taken',
    volvo1: false,
    volvo2: false,
    volvo3: false,
    volvo4: false,
    hyundai1: false,
    hyundai2: false,
    actionTaken: false,
    toBeTaken: false,
  ),
  Hydraulics(
    title: 'Check Control Valve & hyd. Motor for Leakage',
    volvo20: 'Mech. VOLVO-20',
    volvo21: 'Mech. VOLVO-21',
    volvo22: 'Mech. VOLVO-22',
    volvo23: 'Mech. VOLVO-23',
    hyundai390: 'Mech. HYUNDAI- 390',
    hyundai210: 'Mech. HYUNDAI-210',
    action: 'Action taken / to be taken',
    volvo1: false,
    volvo2: false,
    volvo3: false,
    volvo4: false,
    hyundai1: false,
    hyundai2: false,
    actionTaken: false,
    toBeTaken: false,
  ),
  Hydraulics(
    title: 'Check Swing device slew ring for leakage',
    volvo20: 'Mech. VOLVO-20',
    volvo21: 'Mech. VOLVO-21',
    volvo22: 'Mech. VOLVO-22',
    volvo23: 'Mech. VOLVO-23',
    hyundai390: 'Mech. HYUNDAI- 390',
    hyundai210: 'Mech. HYUNDAI-210',
    action: 'Action taken / to be taken',
    volvo1: false,
    volvo2: false,
    volvo3: false,
    volvo4: false,
    hyundai1: false,
    hyundai2: false,
    actionTaken: false,
    toBeTaken: false,
  ),
  Hydraulics(
    title: 'Inspect swivel join, joy stick for leakage',
    volvo20: 'Mech. VOLVO-20',
    volvo21: 'Mech. VOLVO-21',
    volvo22: 'Mech. VOLVO-22',
    volvo23: 'Mech. VOLVO-23',
    hyundai390: 'Mech. HYUNDAI- 390',
    hyundai210: 'Mech. HYUNDAI-210',
    action: 'Action taken / to be taken',
    volvo1: false,
    volvo2: false,
    volvo3: false,
    volvo4: false,
    hyundai1: false,
    hyundai2: false,
    actionTaken: false,
    toBeTaken: false,
  ),
  Hydraulics(
    title: 'Underneath Machine for leakages',
    volvo20: 'Mech. VOLVO-20',
    volvo21: 'Mech. VOLVO-21',
    volvo22: 'Mech. VOLVO-22',
    volvo23: 'Mech. VOLVO-23',
    hyundai390: 'Mech. HYUNDAI- 390',
    hyundai210: 'Mech. HYUNDAI-210',
    action: 'Action taken / to be taken',
    volvo1: false,
    volvo2: false,
    volvo3: false,
    volvo4: false,
    hyundai1: false,
    hyundai2: false,
    actionTaken: false,
    toBeTaken: false,
  ),
];
