class PrimeMoverPreStart {
  final String title;
  final String volvo20;
  final String volvo21;
  final String volvo22;
  final String volvo23;
  final String hyundai390;
  final String hyundai210;
  final String action;
  bool volvo1;
  bool volvo2;
  bool volvo3;
  bool volvo4;
  bool hyundai1;
  bool hyundai2;
  bool actionTaken;
  bool toBeTaken;
  PrimeMoverPreStart({
    required this.title,
    required this.volvo20,
    required this.volvo21,
    required this.volvo22,
    required this.volvo23,
    required this.hyundai390,
    required this.hyundai210,
    required this.action,
    required this.volvo1,
    required this.volvo2,
    required this.volvo3,
    required this.volvo4,
    required this.hyundai1,
    required this.hyundai2,
    required this.actionTaken,
    required this.toBeTaken,
  });
}

List<PrimeMoverPreStart> primeMoverPreStart = [
  PrimeMoverPreStart(
    title: 'Engine oil level',
    volvo20: 'Mech. VOLVO-20',
    volvo21: 'Mech. VOLVO-21',
    volvo22: 'Mech. VOLVO-22',
    volvo23: 'Mech. VOLVO-23',
    hyundai390: 'Mech. HYUNDAI- 390',
    hyundai210: 'Mech. HYUNDAI-210',
    action: 'Action taken / to be taken',
    volvo1: false,
    volvo2: false,
    volvo3: false,
    volvo4: false,
    hyundai1: false,
    hyundai2: false,
    actionTaken: false,
    toBeTaken: false,
  ),
  PrimeMoverPreStart(
    title: 'Engine oil Leakage',
    volvo20: 'Mech. VOLVO-20',
    volvo21: 'Mech. VOLVO-21',
    volvo22: 'Mech. VOLVO-22',
    volvo23: 'Mech. VOLVO-23',
    hyundai390: 'Mech. HYUNDAI- 390',
    hyundai210: 'Mech. HYUNDAI-210',
    action: 'Action taken / to be taken',
    volvo1: false,
    volvo2: false,
    volvo3: false,
    volvo4: false,
    hyundai1: false,
    hyundai2: false,
    actionTaken: false,
    toBeTaken: false,
  ),
  PrimeMoverPreStart(
    title: 'Coolant Level',
    volvo20: 'Mech. VOLVO-20',
    volvo21: 'Mech. VOLVO-21',
    volvo22: 'Mech. VOLVO-22',
    volvo23: 'Mech. VOLVO-23',
    hyundai390: 'Mech. HYUNDAI- 390',
    hyundai210: 'Mech. HYUNDAI-210',
    action: 'Action taken / to be taken',
    volvo1: false,
    volvo2: false,
    volvo3: false,
    volvo4: false,
    hyundai1: false,
    hyundai2: false,
    actionTaken: false,
    toBeTaken: false,
  ),
  PrimeMoverPreStart(
    title: 'Coolant leakage',
    volvo20: 'Mech. VOLVO-20',
    volvo21: 'Mech. VOLVO-21',
    volvo22: 'Mech. VOLVO-22',
    volvo23: 'Mech. VOLVO-23',
    hyundai390: 'Mech. HYUNDAI- 390',
    hyundai210: 'Mech. HYUNDAI-210',
    action: 'Action taken / to be taken',
    volvo1: false,
    volvo2: false,
    volvo3: false,
    volvo4: false,
    hyundai1: false,
    hyundai2: false,
    actionTaken: false,
    toBeTaken: false,
  ),
  PrimeMoverPreStart(
    title: 'Fan Belt Condition',
    volvo20: 'Mech. VOLVO-20',
    volvo21: 'Mech. VOLVO-21',
    volvo22: 'Mech. VOLVO-22',
    volvo23: 'Mech. VOLVO-23',
    hyundai390: 'Mech. HYUNDAI- 390',
    hyundai210: 'Mech. HYUNDAI-210',
    action: 'Action taken / to be taken',
    volvo1: false,
    volvo2: false,
    volvo3: false,
    volvo4: false,
    hyundai1: false,
    hyundai2: false,
    actionTaken: false,
    toBeTaken: false,
  ),
  PrimeMoverPreStart(
    title: 'Fan belt tension & Tensioned Level',
    volvo20: 'Mech. VOLVO-20',
    volvo21: 'Mech. VOLVO-21',
    volvo22: 'Mech. VOLVO-22',
    volvo23: 'Mech. VOLVO-23',
    hyundai390: 'Mech. HYUNDAI- 390',
    hyundai210: 'Mech. HYUNDAI-210',
    action: 'Action taken / to be taken',
    volvo1: false,
    volvo2: false,
    volvo3: false,
    volvo4: false,
    hyundai1: false,
    hyundai2: false,
    actionTaken: false,
    toBeTaken: false,
  ),
  PrimeMoverPreStart(
    title: 'Fan leaf condition',
    volvo20: 'Mech. VOLVO-20',
    volvo21: 'Mech. VOLVO-21',
    volvo22: 'Mech. VOLVO-22',
    volvo23: 'Mech. VOLVO-23',
    hyundai390: 'Mech. HYUNDAI- 390',
    hyundai210: 'Mech. HYUNDAI-210',
    action: 'Action taken / to be taken',
    volvo1: false,
    volvo2: false,
    volvo3: false,
    volvo4: false,
    hyundai1: false,
    hyundai2: false,
    actionTaken: false,
    toBeTaken: false,
  ),
  PrimeMoverPreStart(
    title: 'Radiator condition',
    volvo20: 'Mech. VOLVO-20',
    volvo21: 'Mech. VOLVO-21',
    volvo22: 'Mech. VOLVO-22',
    volvo23: 'Mech. VOLVO-23',
    hyundai390: 'Mech. HYUNDAI- 390',
    hyundai210: 'Mech. HYUNDAI-210',
    action: 'Action taken / to be taken',
    volvo1: false,
    volvo2: false,
    volvo3: false,
    volvo4: false,
    hyundai1: false,
    hyundai2: false,
    actionTaken: false,
    toBeTaken: false,
  ),
  PrimeMoverPreStart(
    title: 'Pipeline, Couling & Hoses Condition',
    volvo20: 'Mech. VOLVO-20',
    volvo21: 'Mech. VOLVO-21',
    volvo22: 'Mech. VOLVO-22',
    volvo23: 'Mech. VOLVO-23',
    hyundai390: 'Mech. HYUNDAI- 390',
    hyundai210: 'Mech. HYUNDAI-210',
    action: 'Action taken / to be taken',
    volvo1: false,
    volvo2: false,
    volvo3: false,
    volvo4: false,
    hyundai1: false,
    hyundai2: false,
    actionTaken: false,
    toBeTaken: false,
  ),
  PrimeMoverPreStart(
    title: 'Drain Condensate from water Sepertor',
    volvo20: 'Mech. VOLVO-20',
    volvo21: 'Mech. VOLVO-21',
    volvo22: 'Mech. VOLVO-22',
    volvo23: 'Mech. VOLVO-23',
    hyundai390: 'Mech. HYUNDAI- 390',
    hyundai210: 'Mech. HYUNDAI-210',
    action: 'Action taken / to be taken',
    volvo1: false,
    volvo2: false,
    volvo3: false,
    volvo4: false,
    hyundai1: false,
    hyundai2: false,
    actionTaken: false,
    toBeTaken: false,
  ),
  PrimeMoverPreStart(
    title: 'Fuel Level & Fill Cap Locking',
    volvo20: 'Mech. VOLVO-20',
    volvo21: 'Mech. VOLVO-21',
    volvo22: 'Mech. VOLVO-22',
    volvo23: 'Mech. VOLVO-23',
    hyundai390: 'Mech. HYUNDAI- 390',
    hyundai210: 'Mech. HYUNDAI-210',
    action: 'Action taken / to be taken',
    volvo1: false,
    volvo2: false,
    volvo3: false,
    volvo4: false,
    hyundai1: false,
    hyundai2: false,
    actionTaken: false,
    toBeTaken: false,
  ),
  PrimeMoverPreStart(
    title: 'Fuel Line Leakage',
    volvo20: 'Mech. VOLVO-20',
    volvo21: 'Mech. VOLVO-21',
    volvo22: 'Mech. VOLVO-22',
    volvo23: 'Mech. VOLVO-23',
    hyundai390: 'Mech. HYUNDAI- 390',
    hyundai210: 'Mech. HYUNDAI-210',
    action: 'Action taken / to be taken',
    volvo1: false,
    volvo2: false,
    volvo3: false,
    volvo4: false,
    hyundai1: false,
    hyundai2: false,
    actionTaken: false,
    toBeTaken: false,
  ),
  PrimeMoverPreStart(
    title: 'Engine Mounting condition',
    volvo20: 'Mech. VOLVO-20',
    volvo21: 'Mech. VOLVO-21',
    volvo22: 'Mech. VOLVO-22',
    volvo23: 'Mech. VOLVO-23',
    hyundai390: 'Mech. HYUNDAI- 390',
    hyundai210: 'Mech. HYUNDAI-210',
    action: 'Action taken / to be taken',
    volvo1: false,
    volvo2: false,
    volvo3: false,
    volvo4: false,
    hyundai1: false,
    hyundai2: false,
    actionTaken: false,
    toBeTaken: false,
  ),
  PrimeMoverPreStart(
    title: 'Turbo charger Piping condition',
    volvo20: 'Mech. VOLVO-20',
    volvo21: 'Mech. VOLVO-21',
    volvo22: 'Mech. VOLVO-22',
    volvo23: 'Mech. VOLVO-23',
    hyundai390: 'Mech. HYUNDAI- 390',
    hyundai210: 'Mech. HYUNDAI-210',
    action: 'Action taken / to be taken',
    volvo1: false,
    volvo2: false,
    volvo3: false,
    volvo4: false,
    hyundai1: false,
    hyundai2: false,
    actionTaken: false,
    toBeTaken: false,
  ),
  PrimeMoverPreStart(
    title: 'Turbo charger condition',
    volvo20: 'Mech. VOLVO-20',
    volvo21: 'Mech. VOLVO-21',
    volvo22: 'Mech. VOLVO-22',
    volvo23: 'Mech. VOLVO-23',
    hyundai390: 'Mech. HYUNDAI- 390',
    hyundai210: 'Mech. HYUNDAI-210',
    action: 'Action taken / to be taken',
    volvo1: false,
    volvo2: false,
    volvo3: false,
    volvo4: false,
    hyundai1: false,
    hyundai2: false,
    actionTaken: false,
    toBeTaken: false,
  ),
  PrimeMoverPreStart(
    title: 'Air Filter Element Outer: Cleanliness & condition',
    volvo20: 'Mech. VOLVO-20',
    volvo21: 'Mech. VOLVO-21',
    volvo22: 'Mech. VOLVO-22',
    volvo23: 'Mech. VOLVO-23',
    hyundai390: 'Mech. HYUNDAI- 390',
    hyundai210: 'Mech. HYUNDAI-210',
    action: 'Action taken / to be taken',
    volvo1: false,
    volvo2: false,
    volvo3: false,
    volvo4: false,
    hyundai1: false,
    hyundai2: false,
    actionTaken: false,
    toBeTaken: false,
  ),
  PrimeMoverPreStart(
    title: 'Engine & Mounting Area Cleanliness',
    volvo20: 'Mech. VOLVO-20',
    volvo21: 'Mech. VOLVO-21',
    volvo22: 'Mech. VOLVO-22',
    volvo23: 'Mech. VOLVO-23',
    hyundai390: 'Mech. HYUNDAI- 390',
    hyundai210: 'Mech. HYUNDAI-210',
    action: 'Action taken / to be taken',
    volvo1: false,
    volvo2: false,
    volvo3: false,
    volvo4: false,
    hyundai1: false,
    hyundai2: false,
    actionTaken: false,
    toBeTaken: false,
  ),
];
