class Undercarriage {
  final String title;
  final String volvo20;
  final String volvo21;
  final String volvo22;
  final String volvo23;
  final String hyundai390;
  final String hyundai210;
  final String action;
  bool volvo1;
  bool volvo2;
  bool volvo3;
  bool volvo4;
  bool hyundai1;
  bool hyundai2;
  bool actionTaken;
  bool toBeTaken;
  Undercarriage({
    required this.title,
    required this.volvo20,
    required this.volvo21,
    required this.volvo22,
    required this.volvo23,
    required this.hyundai390,
    required this.hyundai210,
    required this.action,
    required this.volvo1,
    required this.volvo2,
    required this.volvo3,
    required this.volvo4,
    required this.hyundai1,
    required this.hyundai2,
    required this.actionTaken,
    required this.toBeTaken,
  });
}

List<Undercarriage> undercarriage = [
  Undercarriage(
    title: 'Track Rollers Condition (Wear & Damages)',
    volvo20: 'Mech. VOLVO-20',
    volvo21: 'Mech. VOLVO-21',
    volvo22: 'Mech. VOLVO-22',
    volvo23: 'Mech. VOLVO-23',
    hyundai390: 'Mech. HYUNDAI- 390',
    hyundai210: 'Mech. HYUNDAI-210',
    action: 'Action taken / to be taken',
    volvo1: false,
    volvo2: false,
    volvo3: false,
    volvo4: false,
    hyundai1: false,
    hyundai2: false,
    actionTaken: false,
    toBeTaken: false,
  ),
  Undercarriage(
    title: 'Carrier Rollers condition (Wear & Damages)',
    volvo20: 'Mech. VOLVO-20',
    volvo21: 'Mech. VOLVO-21',
    volvo22: 'Mech. VOLVO-22',
    volvo23: 'Mech. VOLVO-23',
    hyundai390: 'Mech. HYUNDAI- 390',
    hyundai210: 'Mech. HYUNDAI-210',
    action: 'Action taken / to be taken',
    volvo1: false,
    volvo2: false,
    volvo3: false,
    volvo4: false,
    hyundai1: false,
    hyundai2: false,
    actionTaken: false,
    toBeTaken: false,
  ),
  Undercarriage(
    title: 'Track Shoe Condition (Wear & Damages)',
    volvo20: 'Mech. VOLVO-20',
    volvo21: 'Mech. VOLVO-21',
    volvo22: 'Mech. VOLVO-22',
    volvo23: 'Mech. VOLVO-23',
    hyundai390: 'Mech. HYUNDAI- 390',
    hyundai210: 'Mech. HYUNDAI-210',
    action: 'Action taken / to be taken',
    volvo1: false,
    volvo2: false,
    volvo3: false,
    volvo4: false,
    hyundai1: false,
    hyundai2: false,
    actionTaken: false,
    toBeTaken: false,
  ),
  Undercarriage(
    title: 'Track Link Condition (Wear & damages)',
    volvo20: 'Mech. VOLVO-20',
    volvo21: 'Mech. VOLVO-21',
    volvo22: 'Mech. VOLVO-22',
    volvo23: 'Mech. VOLVO-23',
    hyundai390: 'Mech. HYUNDAI- 390',
    hyundai210: 'Mech. HYUNDAI-210',
    action: 'Action taken / to be taken',
    volvo1: false,
    volvo2: false,
    volvo3: false,
    volvo4: false,
    hyundai1: false,
    hyundai2: false,
    actionTaken: false,
    toBeTaken: false,
  ),
  Undercarriage(
    title: 'Turret & Frame Inspection for Cracks',
    volvo20: 'Mech. VOLVO-20',
    volvo21: 'Mech. VOLVO-21',
    volvo22: 'Mech. VOLVO-22',
    volvo23: 'Mech. VOLVO-23',
    hyundai390: 'Mech. HYUNDAI- 390',
    hyundai210: 'Mech. HYUNDAI-210',
    action: 'Action taken / to be taken',
    volvo1: false,
    volvo2: false,
    volvo3: false,
    volvo4: false,
    hyundai1: false,
    hyundai2: false,
    actionTaken: false,
    toBeTaken: false,
  ),
  Undercarriage(
    title: 'Sprocket Condition',
    volvo20: 'Mech. VOLVO-20',
    volvo21: 'Mech. VOLVO-21',
    volvo22: 'Mech. VOLVO-22',
    volvo23: 'Mech. VOLVO-23',
    hyundai390: 'Mech. HYUNDAI- 390',
    hyundai210: 'Mech. HYUNDAI-210',
    action: 'Action taken / to be taken',
    volvo1: false,
    volvo2: false,
    volvo3: false,
    volvo4: false,
    hyundai1: false,
    hyundai2: false,
    actionTaken: false,
    toBeTaken: false,
  ),
  Undercarriage(
    title: 'Idler wheel Condition',
    volvo20: 'Mech. VOLVO-20',
    volvo21: 'Mech. VOLVO-21',
    volvo22: 'Mech. VOLVO-22',
    volvo23: 'Mech. VOLVO-23',
    hyundai390: 'Mech. HYUNDAI- 390',
    hyundai210: 'Mech. HYUNDAI-210',
    action: 'Action taken / to be taken',
    volvo1: false,
    volvo2: false,
    volvo3: false,
    volvo4: false,
    hyundai1: false,
    hyundai2: false,
    actionTaken: false,
    toBeTaken: false,
  ),
  Undercarriage(
    title: 'Tightness of track chain',
    volvo20: 'Mech. VOLVO-20',
    volvo21: 'Mech. VOLVO-21',
    volvo22: 'Mech. VOLVO-22',
    volvo23: 'Mech. VOLVO-23',
    hyundai390: 'Mech. HYUNDAI- 390',
    hyundai210: 'Mech. HYUNDAI-210',
    action: 'Action taken / to be taken',
    volvo1: false,
    volvo2: false,
    volvo3: false,
    volvo4: false,
    hyundai1: false,
    hyundai2: false,
    actionTaken: false,
    toBeTaken: false,
  ),
];
